name: Push to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  push-to-azure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Push to Azure DevOps
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        git remote add azure-devops https://<organization>@dev.azure.com/<organization>/<project>/_git/<repository>
        git push azure-devops main
